apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: app-of-apps
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps
    helm: 
      parameters:
      - name: argocd.giropopsSenhas.enabled
        value: "true"
      - name: argocd.randomLogger.enabled
        value: "true" 
    repoURL: https://github.com/dara-cod/descomplicando-gitops-no-kubernetes-argocd.git
    targetRevision: feat/day2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions: 
    - CreateNamespace=true
    - PruneLast=true